# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

mkdocs:
  configuration: python3/ros-noetic-python3-eventdispatch/mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: python3/ros-noetic-python3-eventdispatch/docs/requirements.txt
