[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "eventdispatch"
authors = [{name = "Charlie Yan", email = "cyanatg@gmail.com"}]
dynamic = ["version", "description"]
